### ISSUE TITLE
Unable to control or see lock in HA update.

### ISSUE THREAD

**Issue by blair287** [benleb/surepy#41]
Unable to use the service to set the lock state just generates this error.

https://pastebin.com/30fyb8Jq

Also there is no entity to show the state of the lock anymore.

This is on a friends instance I don't have a flap to test myself.

**Comment by circa1665** [comment]
As described here: https://github.com/home-assistant/core/issues/50135
and here: https://github.com/home-assistant/core/issues/50133

**Comment by benleb** [comment]
Fixed in https://github.com/benleb/surepetcare already, will probably do a PR here at the weekend

**Comment by GermanGiTter** [comment]
The lock status stays still the same (the current status after a re-start).

How will it be updated in Home Assistant?
